# Generated by Django 4.2.13 on 2024-06-20 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Введите сообщение контакта",
                null=True,
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 6, 20, 19, 33, 20, 472425, tzinfo=datetime.timezone.utc
                ),
                help_text="Укажите дату создания",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
