# Generated by Django 4.2.13 on 2024-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_mailing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
    ]
