# Generated by Django 4.2.13 on 2024-06-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_client_owner_mailing_is_active_mailing_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_active",
        ),
    ]
