# Generated by Django 4.2.13 on 2024-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_remove_mailing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная"),
        ),
    ]
