# Generated by Django 4.2.13 on 2024-06-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_mailing_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="owner",
        ),
    ]
