# Generated by Django 4.2.13 on 2024-06-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0007_remove_client_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="client",
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="mailing",
                to="services.client",
                verbose_name="Клиенты для рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("каждые 10 минут", "Каждые 10 минут"),
                    ("раз в день", "Раз в день"),
                    ("раз в неделю", "Раз в неделю"),
                    ("раз в месяц", "Раз в месяц"),
                ],
                default="раз в день",
                max_length=100,
                verbose_name="периодичность",
            ),
        ),
    ]
