# Generated by Django 4.2.13 on 2024-06-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0008_remove_mailing_client_client_owner_mailing_clients_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="message",
        ),
        migrations.AddField(
            model_name="message",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
