# Generated by Django 4.2.13 on 2024-07-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_remove_mailing_message_message_mailing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="mailing",
        ),
        migrations.RemoveField(
            model_name="message",
            name="owner",
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
