# Generated by Django 4.2.13 on 2024-07-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_alter_client_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="mailing",
            field=models.ManyToManyField(
                related_name="client", to="services.mailing", verbose_name="Рассылка"
            ),
        ),
    ]
