# Generated by Django 4.2.13 on 2024-07-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_alter_client_mailing_alter_client_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_deactivate_mailing", "Can deactivate mailing"),
                    ("can_view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="logs",
            name="mailing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.mailing",
                verbose_name="рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="logs",
            name="response",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="ответ почтового сервера",
            ),
        ),
    ]
